version: '3.3'

services:
    project:
        container_name: malware
        image: malware
        build: 
            dockerfile: ./project/docker/base.dockerfile
            context: .
        working_dir: /home/docky/
        volumes:
            - ./project/code:/home/docky/code
            # - ./project/data:/home/docky/data
            - /Volumes/HD_Externo/data:/home/docky/data
        # environment:
        #     - PYTHONPATH=/home/docky/project/lib/
        # ports:
        #     - 8080:8080
        command: "tail -F /dev/null"
        # command: "env3/bin/python project/website/manage.py runserver 0.0.0.0:8080"